sudo: required
language: cpp
compiler: g++
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

before_install:
  - sudo apt remove --purge imagemagick imagemagick-common
  - sudo apt-get update

install:
  - sudo apt-get install cmake pkg-config tree qtbase5-dev liblcms2-dev

script:
  - export CWD=`pwd`
  - MKJOBS=2 STATIC=0 SIMPLE=1 sh share/scripts/build-magick.sh
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j2
  - make DESTDIR="${CWD}/pkg" install
  - tree "${CWD}/pkg"

