language: cpp
compiler: g++
dist: trusty
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install qtbase5-dev qt5-qmake tree libmagick++-dev liblcms2-dev libqt5x11extras5-dev
  
script:
  - export CWD=`pwd`
  - mkdir $CWD/qt5
  - cd $CWD/qt5
  - qmake -qt=qt5 CONFIG+=release PREFIX=/usr ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
