theme: jekyll-theme-minimal
title: Cyan
description: Open source prepress image viewer and converter
logo: https://github.com/rodlie/cyan/raw/master/share/icons/hicolor/256x256/apps/Cyan.png
show_downloads: false
